apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app # Bu servis, etiketi 'flask-app' olan Pod'lara gitsin demek
  ports:
    - protocol: TCP
      port: 80 # Servisin dışarıdan dinlediği port
      targetPort: 5000 # Pod'un içindeki uygulamanın çalıştığı port
  type: NodePort # Minikube/Lokal ortamda uygulamaya ulaşmak için kullanılan tür