apiVersion: v1
kind: Service
metadata:
  name: redis-service # DİKKAT: Flask reçetesine tam olarak bu ismi yazdık!
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379